name: "Frogbot Scan Pull Request"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  # id-token: write

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Update to your required Node.js version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - uses: jfrog/frogbot@v2
        env:
          # [Mandatory]
          JF_URL: ${{ secrets.JF_URL }}

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JF_USER: ${{ secrets.JF_USER }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

          # [Mandatory]
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # [Optional, default: "FALSE"]
          JF_FAIL: "FALSE"

          # [Optional]
          # You can add other optional parameters here as needed.
          # For example:
          # JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
          # JF_EMAIL_RECEIVERS: "example@example.com"

          # Additional environment variables can be added here as needed.
